// ============================================
// BIST Varlık Veritabanı - Borsa İstanbul
// Hisse Senetleri, Fonlar (BYF/ETF)
// ============================================

export interface BistAsset {
  symbol: string;
  name: string;
  shortName: string;
}

// Tüm BIST Hisse Senetleri (611 adet)
export const BIST_ALL_STOCKS: BistAsset[] = [
  { symbol: 'A1CAP.IS', name: 'A1 Capital', shortName: 'A1CAP' },
  { symbol: 'A1YEN.IS', name: 'Kartal Yenilenebili Enerji', shortName: 'A1YEN' },
  { symbol: 'AAGYO.IS', name: 'Ağaoğlu GYO', shortName: 'AAGYO' },
  { symbol: 'ACSEL.IS', name: 'Acıselsan Acıpayam Selüloz', shortName: 'ACSEL' },
  { symbol: 'ADEL.IS', name: 'Adel Kalemcilik', shortName: 'ADEL' },
  { symbol: 'ADESE.IS', name: 'Adese AVM', shortName: 'ADESE' },
  { symbol: 'ADGYO.IS', name: 'Adra GYO', shortName: 'ADGYO' },
  { symbol: 'AEFES.IS', name: 'Anadolu Efes', shortName: 'AEFES' },
  { symbol: 'AFYON.IS', name: 'Afyon Çimento', shortName: 'AFYON' },
  { symbol: 'AGESA.IS', name: 'Agesa Hayat ve Emeklilik', shortName: 'AGESA' },
  { symbol: 'AGHOL.IS', name: 'Anadolu Grubu Holding', shortName: 'AGHOL' },
  { symbol: 'AGROT.IS', name: 'Agrotech Yüksek Teknoloji', shortName: 'AGROT' },
  { symbol: 'AGYO.IS', name: 'Atakule GYO', shortName: 'AGYO' },
  { symbol: 'AHGAZ.IS', name: 'Ahlatçı Doğalgaz', shortName: 'AHGAZ' },
  { symbol: 'AHSGY.IS', name: 'Ahes GYO', shortName: 'AHSGY' },
  { symbol: 'AKBNK.IS', name: 'Akbank', shortName: 'AKBNK' },
  { symbol: 'AKCNS.IS', name: 'Akçansa', shortName: 'AKCNS' },
  { symbol: 'AKENR.IS', name: 'Akenerji', shortName: 'AKENR' },
  { symbol: 'AKFGY.IS', name: 'Akfen GYO', shortName: 'AKFGY' },
  { symbol: 'AKFIS.IS', name: 'Akfen İnşaat', shortName: 'AKFIS' },
  { symbol: 'AKFYE.IS', name: 'Akfen Yenilenebilir Enerji', shortName: 'AKFYE' },
  { symbol: 'AKGRT.IS', name: 'Aksigorta', shortName: 'AKGRT' },
  { symbol: 'AKHAN.IS', name: 'Akhan Un', shortName: 'AKHAN' },
  { symbol: 'AKMGY.IS', name: 'Akmerkez GYO', shortName: 'AKMGY' },
  { symbol: 'AKSA.IS', name: 'Aksa', shortName: 'AKSA' },
  { symbol: 'AKSEN.IS', name: 'Aksa Enerji', shortName: 'AKSEN' },
  { symbol: 'AKSGY.IS', name: 'Akis GYO', shortName: 'AKSGY' },
  { symbol: 'AKSUE.IS', name: 'Aksu Enerji', shortName: 'AKSUE' },
  { symbol: 'AKYHO.IS', name: 'Akdeniz Yatırım Holding', shortName: 'AKYHO' },
  { symbol: 'ALARK.IS', name: 'Alarko Holding', shortName: 'ALARK' },
  { symbol: 'ALBRK.IS', name: 'Albaraka Türk', shortName: 'ALBRK' },
  { symbol: 'ALCAR.IS', name: 'Alarko Carrier', shortName: 'ALCAR' },
  { symbol: 'ALCTL.IS', name: 'Alcatel Teletaş', shortName: 'ALCTL' },
  { symbol: 'ALFAS.IS', name: 'Alfa Solar', shortName: 'ALFAS' },
  { symbol: 'ALGYO.IS', name: 'Alarko GYO', shortName: 'ALGYO' },
  { symbol: 'ALKA.IS', name: 'Alkim Kağıt', shortName: 'ALKA' },
  { symbol: 'ALKIM.IS', name: 'Alkim', shortName: 'ALKIM' },
  { symbol: 'ALKLC.IS', name: 'Altınkılıç Gıda', shortName: 'ALKLC' },
  { symbol: 'ALTNY.IS', name: 'Altınay Savunma', shortName: 'ALTNY' },
  { symbol: 'ALVES.IS', name: 'Alves Kablo', shortName: 'ALVES' },
  { symbol: 'ANELE.IS', name: 'Anel Elektrik', shortName: 'ANELE' },
  { symbol: 'ANGEN.IS', name: 'Anatolia Biyoteknoloji', shortName: 'ANGEN' },
  { symbol: 'ANHYT.IS', name: 'Anadolu Hayat Emeklilik A.Ş.', shortName: 'ANHYT' },
  { symbol: 'ANSGR.IS', name: 'Anadolu Sigorta', shortName: 'ANSGR' },
  { symbol: 'ARASE.IS', name: 'Doğu Aras Enerji', shortName: 'ARASE' },
  { symbol: 'ARCLK.IS', name: 'Arçelik', shortName: 'ARCLK' },
  { symbol: 'ARDYZ.IS', name: 'ARD Grup Bilişim', shortName: 'ARDYZ' },
  { symbol: 'ARENA.IS', name: 'Arena Bilgisayar', shortName: 'ARENA' },
  { symbol: 'ARFYE.IS', name: 'Arf Bio Enerji', shortName: 'ARFYE' },
  { symbol: 'ARMGD.IS', name: 'Armada Gıda', shortName: 'ARMGD' },
  { symbol: 'ARSAN.IS', name: 'Arsan Holding', shortName: 'ARSAN' },
  { symbol: 'ARTMS.IS', name: 'Artemis Halı', shortName: 'ARTMS' },
  { symbol: 'ARZUM.IS', name: 'Arzum Ev Aletleri', shortName: 'ARZUM' },
  { symbol: 'ASELS.IS', name: 'Aselsan', shortName: 'ASELS' },
  { symbol: 'ASGYO.IS', name: 'Asce GYO', shortName: 'ASGYO' },
  { symbol: 'ASTOR.IS', name: 'Astor Enerji', shortName: 'ASTOR' },
  { symbol: 'ASUZU.IS', name: 'Anadolu Isuzu', shortName: 'ASUZU' },
  { symbol: 'ATAGY.IS', name: 'Ata GYO', shortName: 'ATAGY' },
  { symbol: 'ATAKP.IS', name: 'Atakey Patates', shortName: 'ATAKP' },
  { symbol: 'ATATP.IS', name: 'ATP Bilgisayar', shortName: 'ATATP' },
  { symbol: 'ATATR.IS', name: 'Ata Turizm', shortName: 'ATATR' },
  { symbol: 'ATEKS.IS', name: 'Akın Tekstil', shortName: 'ATEKS' },
  { symbol: 'ATLAS.IS', name: 'Atlas YO', shortName: 'ATLAS' },
  { symbol: 'ATSYH.IS', name: 'Atlantis YO', shortName: 'ATSYH' },
  { symbol: 'AVGYO.IS', name: 'Avrasya YO', shortName: 'AVGYO' },
  { symbol: 'AVHOL.IS', name: 'Avrupa Yatırım Holding', shortName: 'AVHOL' },
  { symbol: 'AVOD.IS', name: 'Avod Kurutulmuş Gıda', shortName: 'AVOD' },
  { symbol: 'AVPGY.IS', name: 'Avrupakent GYO', shortName: 'AVPGY' },
  { symbol: 'AVTUR.IS', name: 'Avrasya Petrol&Turistik Tesis', shortName: 'AVTUR' },
  { symbol: 'AYCES.IS', name: 'Altınyunus Çesme', shortName: 'AYCES' },
  { symbol: 'AYDEM.IS', name: 'Aydem Enerji', shortName: 'AYDEM' },
  { symbol: 'AYEN.IS', name: 'Ayen Enerji', shortName: 'AYEN' },
  { symbol: 'AYES.IS', name: 'Ayes Çelik Hasır & Çit', shortName: 'AYES' },
  { symbol: 'AYGAZ.IS', name: 'Aygaz', shortName: 'AYGAZ' },
  { symbol: 'AZTEK.IS', name: 'Aztek Teknoloji', shortName: 'AZTEK' },
  { symbol: 'BAGFS.IS', name: 'Bandırma Gübre Fabrikaları A.Ş', shortName: 'BAGFS' },
  { symbol: 'BAHKM.IS', name: 'Bahadır Kimya', shortName: 'BAHKM' },
  { symbol: 'BAKAB.IS', name: 'Bak Ambalaj', shortName: 'BAKAB' },
  { symbol: 'BALAT.IS', name: 'Balatacılar Balatacılık', shortName: 'BALAT' },
  { symbol: 'BALSU.IS', name: 'Balsu Gıda', shortName: 'BALSU' },
  { symbol: 'BANVT.IS', name: 'Banvit', shortName: 'BANVT' },
  { symbol: 'BARMA.IS', name: 'Barem Ambalaj', shortName: 'BARMA' },
  { symbol: 'BASCM.IS', name: 'Baştaş Başkent Çimento Sanayi', shortName: 'BASCM' },
  { symbol: 'BASGZ.IS', name: 'Başkent Doğalgaz', shortName: 'BASGZ' },
  { symbol: 'BAYRK.IS', name: 'Bayrak EBT Taban', shortName: 'BAYRK' },
  { symbol: 'BEGYO.IS', name: 'Batı Ege GYO', shortName: 'BEGYO' },
  { symbol: 'BERA.IS', name: 'Bera Holding', shortName: 'BERA' },
  { symbol: 'BESLR.IS', name: 'Besler Gıda', shortName: 'BESLR' },
  { symbol: 'BESTE.IS', name: 'Best Brands Grup', shortName: 'BESTE' },
  { symbol: 'BEYAZ.IS', name: 'Beyaz Filo', shortName: 'BEYAZ' },
  { symbol: 'BFREN.IS', name: 'Bosch Fren', shortName: 'BFREN' },
  { symbol: 'BIENY.IS', name: 'Bien Yapı', shortName: 'BIENY' },
  { symbol: 'BIGCH.IS', name: 'BigChefs', shortName: 'BIGCH' },
  { symbol: 'BIGEN.IS', name: 'Birleşim Grup Enerji', shortName: 'BIGEN' },
  { symbol: 'BIGTK.IS', name: 'Big Medya', shortName: 'BIGTK' },
  { symbol: 'BIMAS.IS', name: 'Bim Birleşik Mağazalar A.Ş', shortName: 'BIMAS' },
  { symbol: 'BINBN.IS', name: 'BinBin', shortName: 'BINBN' },
  { symbol: 'BINHO.IS', name: '1000 Yatırımlar', shortName: 'BINHO' },
  { symbol: 'BIOEN.IS', name: 'Biotrend Enerji', shortName: 'BIOEN' },
  { symbol: 'BIZIM.IS', name: 'Bizim Toptan', shortName: 'BIZIM' },
  { symbol: 'BJKAS.IS', name: 'Beşiktaş', shortName: 'BJKAS' },
  { symbol: 'BLCYT.IS', name: 'Bilici Yatırım', shortName: 'BLCYT' },
  { symbol: 'BLUME.IS', name: 'Blume Metal Kimya', shortName: 'BLUME' },
  { symbol: 'BMSCH.IS', name: 'BMS Çelik Hasır', shortName: 'BMSCH' },
  { symbol: 'BMSTL.IS', name: 'BMS Birleşik Metal', shortName: 'BMSTL' },
  { symbol: 'BNTAS.IS', name: 'Bantaş Bandırma Ambalaj', shortName: 'BNTAS' },
  { symbol: 'BOBET.IS', name: 'Boğaziçi Beton', shortName: 'BOBET' },
  { symbol: 'BORLS.IS', name: 'Borlease Otomotiv', shortName: 'BORLS' },
  { symbol: 'BORSK.IS', name: 'Bor Şeker', shortName: 'BORSK' },
  { symbol: 'BOSSA.IS', name: 'Bossa', shortName: 'BOSSA' },
  { symbol: 'BRISA.IS', name: 'Brisa', shortName: 'BRISA' },
  { symbol: 'BRKO.IS', name: 'Birko Mensucat', shortName: 'BRKO' },
  { symbol: 'BRKSN.IS', name: 'Berkosan Yalıtım', shortName: 'BRKSN' },
  { symbol: 'BRKVY.IS', name: 'Birikim Varlık', shortName: 'BRKVY' },
  { symbol: 'BRLSM.IS', name: 'Birlesim Mühendislik', shortName: 'BRLSM' },
  { symbol: 'BRMEN.IS', name: 'Birlik Mensucat', shortName: 'BRMEN' },
  { symbol: 'BRSAN.IS', name: 'Borusan Birleşik Boru Fab.', shortName: 'BRSAN' },
  { symbol: 'BRYAT.IS', name: 'Borusan Yatırım', shortName: 'BRYAT' },
  { symbol: 'BSOKE.IS', name: 'Batı Söke Çimento', shortName: 'BSOKE' },
  { symbol: 'BTCIM.IS', name: 'Batıçim', shortName: 'BTCIM' },
  { symbol: 'BUCIM.IS', name: 'Bursa Çimento', shortName: 'BUCIM' },
  { symbol: 'BULGS.IS', name: 'Bulls GSYO', shortName: 'BULGS' },
  { symbol: 'BURCE.IS', name: 'Burçelik', shortName: 'BURCE' },
  { symbol: 'BURVA.IS', name: 'Burçelik Vana Sanayii', shortName: 'BURVA' },
  { symbol: 'BVSAN.IS', name: 'Bülbüloğlu Vinç', shortName: 'BVSAN' },
  { symbol: 'BYDNR.IS', name: 'Baydöner', shortName: 'BYDNR' },
  { symbol: 'CANTE.IS', name: 'Çan2 Termik A.S', shortName: 'CANTE' },
  { symbol: 'CASA.IS', name: 'Casa Emtia Petrol Kim.Tür.AŞ', shortName: 'CASA' },
  { symbol: 'CATES.IS', name: 'Çates Elektrik', shortName: 'CATES' },
  { symbol: 'CCOLA.IS', name: 'Coca-Cola İçecek A.Ş', shortName: 'CCOLA' },
  { symbol: 'CELHA.IS', name: 'Çelik Halat', shortName: 'CELHA' },
  { symbol: 'CEMAS.IS', name: 'Çemaş Döküm', shortName: 'CEMAS' },
  { symbol: 'CEMTS.IS', name: 'Çemtas', shortName: 'CEMTS' },
  { symbol: 'CEMZY.IS', name: 'Cem Zeytin', shortName: 'CEMZY' },
  { symbol: 'CEOEM.IS', name: 'CEO Event Medya', shortName: 'CEOEM' },
  { symbol: 'CGCAM.IS', name: 'Çağdaş Cam', shortName: 'CGCAM' },
  { symbol: 'CIMSA.IS', name: 'Çimsa', shortName: 'CIMSA' },
  { symbol: 'CLEBI.IS', name: 'Çelebi', shortName: 'CLEBI' },
  { symbol: 'CMBTN.IS', name: 'Çimbeton', shortName: 'CMBTN' },
  { symbol: 'CMENT.IS', name: 'Çimentaş', shortName: 'CMENT' },
  { symbol: 'CONSE.IS', name: 'Consus Enerji', shortName: 'CONSE' },
  { symbol: 'COSMO.IS', name: 'Cosmos Yatırım Holding', shortName: 'COSMO' },
  { symbol: 'CRDFA.IS', name: 'Creditwest Faktoring', shortName: 'CRDFA' },
  { symbol: 'CRFSA.IS', name: 'Carrefoursa', shortName: 'CRFSA' },
  { symbol: 'CUSAN.IS', name: 'Çuhadaroğlu Metal', shortName: 'CUSAN' },
  { symbol: 'CVKMD.IS', name: 'Cvk Maden', shortName: 'CVKMD' },
  { symbol: 'CWENE.IS', name: 'Cw Enerji', shortName: 'CWENE' },
  { symbol: 'DAGI.IS', name: 'Dagi Giyim', shortName: 'DAGI' },
  { symbol: 'DAPGM.IS', name: 'Dap Gayrimenkul', shortName: 'DAPGM' },
  { symbol: 'DARDL.IS', name: 'Dardanel', shortName: 'DARDL' },
  { symbol: 'DCTTR.IS', name: 'Dct Trading', shortName: 'DCTTR' },
  { symbol: 'DENGE.IS', name: 'Denge Holding', shortName: 'DENGE' },
  { symbol: 'DERHL.IS', name: 'Derlüks Yatırım Holding', shortName: 'DERHL' },
  { symbol: 'DERIM.IS', name: 'Derimod', shortName: 'DERIM' },
  { symbol: 'DESA.IS', name: 'Desa Deri Sanayii', shortName: 'DESA' },
  { symbol: 'DESPC.IS', name: 'Despec Bilgisayar', shortName: 'DESPC' },
  { symbol: 'DEVA.IS', name: 'Deva Holding', shortName: 'DEVA' },
  { symbol: 'DGATE.IS', name: 'Datagate', shortName: 'DGATE' },
  { symbol: 'DGGYO.IS', name: 'Doğuş GYO', shortName: 'DGGYO' },
  { symbol: 'DGNMO.IS', name: 'Doğanlar Mobilya', shortName: 'DGNMO' },
  { symbol: 'DIRIT.IS', name: 'Diriteks Diriliş Tekstil', shortName: 'DIRIT' },
  { symbol: 'DITAS.IS', name: 'Ditaş BDY', shortName: 'DITAS' },
  { symbol: 'DMRGD.IS', name: 'DMR Unlu Mamüller', shortName: 'DMRGD' },
  { symbol: 'DMSAS.IS', name: 'Demisaş', shortName: 'DMSAS' },
  { symbol: 'DNISI.IS', name: 'Dinamik Isı Yalıtım', shortName: 'DNISI' },
  { symbol: 'DOAS.IS', name: 'Doğuş Otomotiv', shortName: 'DOAS' },
  { symbol: 'DOCO.IS', name: 'DO & CO Aktiengesellschaft', shortName: 'DOCO' },
  { symbol: 'DOFER.IS', name: 'Dofer Yapı', shortName: 'DOFER' },
  { symbol: 'DOFRB.IS', name: 'Dof Robotik', shortName: 'DOFRB' },
  { symbol: 'DOGUB.IS', name: 'Doğusan', shortName: 'DOGUB' },
  { symbol: 'DOHOL.IS', name: 'Doğan Holding', shortName: 'DOHOL' },
  { symbol: 'DOKTA.IS', name: 'Döktaş Dökümcülük', shortName: 'DOKTA' },
  { symbol: 'DSTKF.IS', name: 'Destek Finans Faktoring', shortName: 'DSTKF' },
  { symbol: 'DUNYH.IS', name: 'Dünya Holding', shortName: 'DUNYH' },
  { symbol: 'DURDO.IS', name: 'Duran Doğan Basım', shortName: 'DURDO' },
  { symbol: 'DURKN.IS', name: 'Durukan Şekerleme', shortName: 'DURKN' },
  { symbol: 'DYOBY.IS', name: 'DYO Boya', shortName: 'DYOBY' },
  { symbol: 'DZGYO.IS', name: 'Deniz GYO', shortName: 'DZGYO' },
  { symbol: 'EBEBK.IS', name: 'Ebebek', shortName: 'EBEBK' },
  { symbol: 'ECILC.IS', name: 'Eczacıbaşı İlaç', shortName: 'ECILC' },
  { symbol: 'ECOGR.IS', name: 'Ecogreen', shortName: 'ECOGR' },
  { symbol: 'ECZYT.IS', name: 'Eczacıbaşı Yatırım', shortName: 'ECZYT' },
  { symbol: 'EDATA.IS', name: 'E-Data Teknoloji', shortName: 'EDATA' },
  { symbol: 'EDIP.IS', name: 'Edip Gayrimenkul Yat. San.', shortName: 'EDIP' },
  { symbol: 'EFOR.IS', name: 'Efor Yat. San.', shortName: 'EFOR' },
  { symbol: 'EGEEN.IS', name: 'Ege Endüstri', shortName: 'EGEEN' },
  { symbol: 'EGEGY.IS', name: 'Egeyapı GYO', shortName: 'EGEGY' },
  { symbol: 'EGEPO.IS', name: 'Egepol Hastanesi', shortName: 'EGEPO' },
  { symbol: 'EGGUB.IS', name: 'Ege Gübre', shortName: 'EGGUB' },
  { symbol: 'EGPRO.IS', name: 'Ege Profil', shortName: 'EGPRO' },
  { symbol: 'EGSER.IS', name: 'Ege Seramik', shortName: 'EGSER' },
  { symbol: 'EKDMR.IS', name: 'Ekinciler', shortName: 'EKDMR' },
  { symbol: 'EKGYO.IS', name: 'Emlak Konut GYO', shortName: 'EKGYO' },
  { symbol: 'EKIZ.IS', name: 'Ekiz Yağ ve Sabun', shortName: 'EKIZ' },
  { symbol: 'EKOS.IS', name: 'Ekos Teknoloji', shortName: 'EKOS' },
  { symbol: 'EKSUN.IS', name: 'Eksun Gıda', shortName: 'EKSUN' },
  { symbol: 'ELITE.IS', name: 'Elite Organik Gıda', shortName: 'ELITE' },
  { symbol: 'EMKEL.IS', name: 'Emek Elektrik', shortName: 'EMKEL' },
  { symbol: 'EMNIS.IS', name: 'Eminiş Ambalaj', shortName: 'EMNIS' },
  { symbol: 'EMPAE.IS', name: 'Empa Elektronik', shortName: 'EMPAE' },
  { symbol: 'ENDAE.IS', name: 'Enda Enerji', shortName: 'ENDAE' },
  { symbol: 'ENERY.IS', name: 'Enerya Enerji', shortName: 'ENERY' },
  { symbol: 'ENJSA.IS', name: 'Enerjisa Enerji', shortName: 'ENJSA' },
  { symbol: 'ENKAI.IS', name: 'Enka İnşaat', shortName: 'ENKAI' },
  { symbol: 'ENPRA.IS', name: 'Enpara', shortName: 'ENPRA' },
  { symbol: 'ENSRI.IS', name: 'Ensari Deri', shortName: 'ENSRI' },
  { symbol: 'ENTRA.IS', name: 'Ic Enterra Yenilenebilir', shortName: 'ENTRA' },
  { symbol: 'EPLAS.IS', name: 'Egeplast', shortName: 'EPLAS' },
  { symbol: 'ERBOS.IS', name: 'Erbosan', shortName: 'ERBOS' },
  { symbol: 'ERCB.IS', name: 'Erciyas Çelik Boru', shortName: 'ERCB' },
  { symbol: 'EREGL.IS', name: 'Ereğli Demir Çelik', shortName: 'EREGL' },
  { symbol: 'ERSU.IS', name: 'Ersu Gıda', shortName: 'ERSU' },
  { symbol: 'ESCAR.IS', name: 'Escar Filo', shortName: 'ESCAR' },
  { symbol: 'ESCOM.IS', name: 'Escort Teknoloji', shortName: 'ESCOM' },
  { symbol: 'ESEN.IS', name: 'Esenboğa Elektrik', shortName: 'ESEN' },
  { symbol: 'ETILR.IS', name: 'Etiler Gıda', shortName: 'ETILR' },
  { symbol: 'ETYAT.IS', name: 'Euro Trend Yatırım', shortName: 'ETYAT' },
  { symbol: 'EUHOL.IS', name: 'Euro Yatırım', shortName: 'EUHOL' },
  { symbol: 'EUKYO.IS', name: 'Euro Kapital Yatırım Ortaklığı', shortName: 'EUKYO' },
  { symbol: 'EUPWR.IS', name: 'Europower Enerji', shortName: 'EUPWR' },
  { symbol: 'EUREN.IS', name: 'Europen Endüstri', shortName: 'EUREN' },
  { symbol: 'EUYO.IS', name: 'Euro Menkul', shortName: 'EUYO' },
  { symbol: 'EYGYO.IS', name: 'EYG Gayrimenkul', shortName: 'EYGYO' },
  { symbol: 'FADE.IS', name: 'Fade Gıda Yatırım', shortName: 'FADE' },
  { symbol: 'FENER.IS', name: 'Fenerbahce Futbol A.Ş.', shortName: 'FENER' },
  { symbol: 'FLAP.IS', name: 'Flap Kongre Hiz.Oto.Tur.A.Ş', shortName: 'FLAP' },
  { symbol: 'FMIZP.IS', name: 'F-M İzmit Piston', shortName: 'FMIZP' },
  { symbol: 'FONET.IS', name: 'Fonet Bilgi Teknolojileri', shortName: 'FONET' },
  { symbol: 'FORMT.IS', name: 'Formet Metal ve Cam Sanayii', shortName: 'FORMT' },
  { symbol: 'FORTE.IS', name: 'Forte Bilgi İletişim', shortName: 'FORTE' },
  { symbol: 'FRIGO.IS', name: 'Frigo Pak Gıda', shortName: 'FRIGO' },
  { symbol: 'FRMPL.IS', name: 'Formül Plastik', shortName: 'FRMPL' },
  { symbol: 'FROTO.IS', name: 'Ford Otosan', shortName: 'FROTO' },
  { symbol: 'FZLGY.IS', name: 'Fuzul Gayrimenkul', shortName: 'FZLGY' },
  { symbol: 'GARAN.IS', name: 'Garanti Bankası', shortName: 'GARAN' },
  { symbol: 'GARFA.IS', name: 'Garanti BBVA Faktoring', shortName: 'GARFA' },
  { symbol: 'GATEG.IS', name: 'Gate Group', shortName: 'GATEG' },
  { symbol: 'GEDIK.IS', name: 'Gedik Yatırım', shortName: 'GEDIK' },
  { symbol: 'GEDZA.IS', name: 'Gediz Ambalaj Sanayi', shortName: 'GEDZA' },
  { symbol: 'GENIL.IS', name: 'Gen İlaç', shortName: 'GENIL' },
  { symbol: 'GENKM.IS', name: 'Gentaş Kimya', shortName: 'GENKM' },
  { symbol: 'GENTS.IS', name: 'Gentaş', shortName: 'GENTS' },
  { symbol: 'GEREL.IS', name: 'Gersan Elektrik', shortName: 'GEREL' },
  { symbol: 'GESAN.IS', name: 'Girişim Elektrik', shortName: 'GESAN' },
  { symbol: 'GIPTA.IS', name: 'Gıpta', shortName: 'GIPTA' },
  { symbol: 'GLBMD.IS', name: 'Global Menkul Değerler', shortName: 'GLBMD' },
  { symbol: 'GLCVY.IS', name: 'Gelecek Varlık Yön.', shortName: 'GLCVY' },
  { symbol: 'GLRMK.IS', name: 'Gülermak Ağır Sanayi', shortName: 'GLRMK' },
  { symbol: 'GLRYH.IS', name: 'Güler Yatırım Holding', shortName: 'GLRYH' },
  { symbol: 'GLYHO.IS', name: 'Global Yatırım Holding', shortName: 'GLYHO' },
  { symbol: 'GMTAS.IS', name: 'Gimat Mağazacılık', shortName: 'GMTAS' },
  { symbol: 'GOKNR.IS', name: 'Göknur Gıda', shortName: 'GOKNR' },
  { symbol: 'GOLTS.IS', name: 'Göltaş Çimento', shortName: 'GOLTS' },
  { symbol: 'GOODY.IS', name: 'Goodyear', shortName: 'GOODY' },
  { symbol: 'GOZDE.IS', name: 'Gözde Girisim Sermayesi', shortName: 'GOZDE' },
  { symbol: 'GRNYO.IS', name: 'Garanti YO', shortName: 'GRNYO' },
  { symbol: 'GRSEL.IS', name: 'Gürsel Taşımacılık', shortName: 'GRSEL' },
  { symbol: 'GRTHO.IS', name: 'GrainTurk Tarım', shortName: 'GRTHO' },
  { symbol: 'GSDDE.IS', name: 'GSD Denizcilik Gayrimenkul İnş', shortName: 'GSDDE' },
  { symbol: 'GSDHO.IS', name: 'GSD Holding A.Ş.', shortName: 'GSDHO' },
  { symbol: 'GSRAY.IS', name: 'Galatasaray Sportif A.Ş', shortName: 'GSRAY' },
  { symbol: 'GUBRF.IS', name: 'Gübre Fabrikaları', shortName: 'GUBRF' },
  { symbol: 'GUNDG.IS', name: 'Gündoğdu Gıda', shortName: 'GUNDG' },
  { symbol: 'GWIND.IS', name: 'Galata Wind Enerji', shortName: 'GWIND' },
  { symbol: 'GZNMI.IS', name: 'Gezinomi Seyahat', shortName: 'GZNMI' },
  { symbol: 'HALKB.IS', name: 'Halkbank', shortName: 'HALKB' },
  { symbol: 'HATEK.IS', name: 'Hateks Hatay Tekstil', shortName: 'HATEK' },
  { symbol: 'HATSN.IS', name: 'Hat-San', shortName: 'HATSN' },
  { symbol: 'HDFGS.IS', name: 'Hedef Girişim Sermayesi', shortName: 'HDFGS' },
  { symbol: 'HEDEF.IS', name: 'Hedef Holding', shortName: 'HEDEF' },
  { symbol: 'HEKTS.IS', name: 'Hektaş', shortName: 'HEKTS' },
  { symbol: 'HKTM.IS', name: 'Hidropar', shortName: 'HKTM' },
  { symbol: 'HLGYO.IS', name: 'Halk GYO', shortName: 'HLGYO' },
  { symbol: 'HOROZ.IS', name: 'Horoz Lojistik', shortName: 'HOROZ' },
  { symbol: 'HRKET.IS', name: 'Hareket Proje', shortName: 'HRKET' },
  { symbol: 'HTTBT.IS', name: 'Hitit Bilgisayar', shortName: 'HTTBT' },
  { symbol: 'HUBVC.IS', name: 'Hub Girişim Ser. Y.O.', shortName: 'HUBVC' },
  { symbol: 'HUNER.IS', name: 'Hun Enerji', shortName: 'HUNER' },
  { symbol: 'HURGZ.IS', name: 'Hürriyet', shortName: 'HURGZ' },
  { symbol: 'ICBCT.IS', name: 'ICBC Turkey Bank', shortName: 'ICBCT' },
  { symbol: 'ICUGS.IS', name: 'Icu Girişim Ser. Y.O.', shortName: 'ICUGS' },
  { symbol: 'IDGYO.IS', name: 'İdealist GYO', shortName: 'IDGYO' },
  { symbol: 'IEYHO.IS', name: 'Işıklar Enerji ve Yapı Holding', shortName: 'IEYHO' },
  { symbol: 'IHAAS.IS', name: 'İhlas Haber Ajansı', shortName: 'IHAAS' },
  { symbol: 'IHEVA.IS', name: 'İhlas Ev Aletleri', shortName: 'IHEVA' },
  { symbol: 'IHGZT.IS', name: 'İhlas Gazetecilik', shortName: 'IHGZT' },
  { symbol: 'IHLAS.IS', name: 'İhlas Holding', shortName: 'IHLAS' },
  { symbol: 'IHLGM.IS', name: 'İhlas Gayrimenkul', shortName: 'IHLGM' },
  { symbol: 'IHYAY.IS', name: 'İhlas Yayın Holding', shortName: 'IHYAY' },
  { symbol: 'IMASM.IS', name: 'İmaş Makine', shortName: 'IMASM' },
  { symbol: 'INDES.IS', name: 'İndeks Bilgisayar', shortName: 'INDES' },
  { symbol: 'INFO.IS', name: 'İnfo Yatırım', shortName: 'INFO' },
  { symbol: 'INGRM.IS', name: 'İngram Bilişim', shortName: 'INGRM' },
  { symbol: 'INTEK.IS', name: 'Innosa Teknoloji', shortName: 'INTEK' },
  { symbol: 'INTEM.IS', name: 'İntema', shortName: 'INTEM' },
  { symbol: 'INVEO.IS', name: 'İnveo Yatırım Holding', shortName: 'INVEO' },
  { symbol: 'INVES.IS', name: 'Investco Holding', shortName: 'INVES' },
  { symbol: 'ISATR.IS', name: 'İş Bankası (A)', shortName: 'ISATR' },
  { symbol: 'ISBIR.IS', name: 'İşbir Holding', shortName: 'ISBIR' },
  { symbol: 'ISBTR.IS', name: 'İş Bankası (B)', shortName: 'ISBTR' },
  { symbol: 'ISCTR.IS', name: 'İş Bankası (C)', shortName: 'ISCTR' },
  { symbol: 'ISDMR.IS', name: 'İskenderun Demir Çelik', shortName: 'ISDMR' },
  { symbol: 'ISFIN.IS', name: 'İş Finansal Kiralama', shortName: 'ISFIN' },
  { symbol: 'ISGSY.IS', name: 'İş Girişim', shortName: 'ISGSY' },
  { symbol: 'ISGYO.IS', name: 'İş GYO', shortName: 'ISGYO' },
  { symbol: 'ISKPL.IS', name: 'Işıklar Plastik', shortName: 'ISKPL' },
  { symbol: 'ISKUR.IS', name: 'İş Bankası Kurucu', shortName: 'ISKUR' },
  { symbol: 'ISMEN.IS', name: 'İş Yatırım', shortName: 'ISMEN' },
  { symbol: 'ISSEN.IS', name: 'İşbir Sentetik', shortName: 'ISSEN' },
  { symbol: 'ISYAT.IS', name: 'İs YO', shortName: 'ISYAT' },
  { symbol: 'IZENR.IS', name: 'İzdemir Enerji', shortName: 'IZENR' },
  { symbol: 'IZFAS.IS', name: 'İzmir Fırça', shortName: 'IZFAS' },
  { symbol: 'IZINV.IS', name: 'İz Yatırım Holding', shortName: 'IZINV' },
  { symbol: 'IZMDC.IS', name: 'İzmir Demir Çelik', shortName: 'IZMDC' },
  { symbol: 'JANTS.IS', name: 'Jantsa Jant', shortName: 'JANTS' },
  { symbol: 'KAPLM.IS', name: 'Kaplamin', shortName: 'KAPLM' },
  { symbol: 'KAREL.IS', name: 'Karel Elektronik', shortName: 'KAREL' },
  { symbol: 'KARSN.IS', name: 'Karsan Otomotiv', shortName: 'KARSN' },
  { symbol: 'KARTN.IS', name: 'Kartonsan', shortName: 'KARTN' },
  { symbol: 'KATMR.IS', name: 'Katmerciler Araç Üstü Ekipman', shortName: 'KATMR' },
  { symbol: 'KAYSE.IS', name: 'Kayseri Şeker', shortName: 'KAYSE' },
  { symbol: 'KBORU.IS', name: 'Kuzey Boru', shortName: 'KBORU' },
  { symbol: 'KCAER.IS', name: 'Kocaer Çelik Sanayi', shortName: 'KCAER' },
  { symbol: 'KCHOL.IS', name: 'Koç Holding', shortName: 'KCHOL' },
  { symbol: 'KENT.IS', name: 'Kent Gıda', shortName: 'KENT' },
  { symbol: 'KERVN.IS', name: 'Kervansaray Yat. Holding', shortName: 'KERVN' },
  { symbol: 'KFEIN.IS', name: 'Kafein Yazılım', shortName: 'KFEIN' },
  { symbol: 'KGYO.IS', name: 'Koray GYO', shortName: 'KGYO' },
  { symbol: 'KIMMR.IS', name: 'Ersan Alışveriş Hizmetleri', shortName: 'KIMMR' },
  { symbol: 'KLGYO.IS', name: 'Kiler GYO', shortName: 'KLGYO' },
  { symbol: 'KLKIM.IS', name: 'Kalekim Kimyevi Maddeler', shortName: 'KLKIM' },
  { symbol: 'KLMSN.IS', name: 'Klimasan', shortName: 'KLMSN' },
  { symbol: 'KLNMA.IS', name: 'T. Kalkınma Bankası', shortName: 'KLNMA' },
  { symbol: 'KLRHO.IS', name: 'Kiler Holding', shortName: 'KLRHO' },
  { symbol: 'KLSER.IS', name: 'Kaleseramik', shortName: 'KLSER' },
  { symbol: 'KLSYN.IS', name: 'Koleksiyon Mobilya', shortName: 'KLSYN' },
  { symbol: 'KLYPV.IS', name: 'Kalyon Güneş Teknolojileri', shortName: 'KLYPV' },
  { symbol: 'KMPUR.IS', name: 'Kimteks Poliüretan', shortName: 'KMPUR' },
  { symbol: 'KNFRT.IS', name: 'Konfrut Gıda', shortName: 'KNFRT' },
  { symbol: 'KOCMT.IS', name: 'Koç Metalurji', shortName: 'KOCMT' },
  { symbol: 'KONKA.IS', name: 'Konya Kağıt', shortName: 'KONKA' },
  { symbol: 'KONTR.IS', name: 'Kontrolmatik Teknoloji', shortName: 'KONTR' },
  { symbol: 'KONYA.IS', name: 'Konya Çimento', shortName: 'KONYA' },
  { symbol: 'KOPOL.IS', name: 'Koza Polyester', shortName: 'KOPOL' },
  { symbol: 'KORDS.IS', name: 'Kordsa Teknik Tekstil', shortName: 'KORDS' },
  { symbol: 'KOTON.IS', name: 'Koton', shortName: 'KOTON' },
  { symbol: 'KRDMA.IS', name: 'Kardemir (A)', shortName: 'KRDMA' },
  { symbol: 'KRDMB.IS', name: 'Kardemir (B)', shortName: 'KRDMB' },
  { symbol: 'KRDMD.IS', name: 'Kardemir (D)', shortName: 'KRDMD' },
  { symbol: 'KRGYO.IS', name: 'Korfez GYO', shortName: 'KRGYO' },
  { symbol: 'KRONT.IS', name: 'Kron Teknoloji', shortName: 'KRONT' },
  { symbol: 'KRPLS.IS', name: 'Koroplast Temizlik Ambalaj', shortName: 'KRPLS' },
  { symbol: 'KRSTL.IS', name: 'Kristal Kola', shortName: 'KRSTL' },
  { symbol: 'KRTEK.IS', name: 'Karsu Tekstil', shortName: 'KRTEK' },
  { symbol: 'KRVGD.IS', name: 'Kervan Gıda', shortName: 'KRVGD' },
  { symbol: 'KSTUR.IS', name: 'Kuştur Turizm', shortName: 'KSTUR' },
  { symbol: 'KTLEV.IS', name: 'Katılımevim', shortName: 'KTLEV' },
  { symbol: 'KTSKR.IS', name: 'Kütahya Şeker', shortName: 'KTSKR' },
  { symbol: 'KUTPO.IS', name: 'Kütahya Porselen', shortName: 'KUTPO' },
  { symbol: 'KUVVA.IS', name: 'Kuvva Gıda', shortName: 'KUVVA' },
  { symbol: 'KUYAS.IS', name: 'Kuyas Yatırım AŞ', shortName: 'KUYAS' },
  { symbol: 'KZBGY.IS', name: 'Kızılbük GYO', shortName: 'KZBGY' },
  { symbol: 'KZGYO.IS', name: 'Kuzugrup GYO', shortName: 'KZGYO' },
  { symbol: 'LIDER.IS', name: 'Lider Turizm', shortName: 'LIDER' },
  { symbol: 'LIDFA.IS', name: 'Lider Faktoring', shortName: 'LIDFA' },
  { symbol: 'LILAK.IS', name: 'Lila Kağıt', shortName: 'LILAK' },
  { symbol: 'LINK.IS', name: 'Link Bilgisayar', shortName: 'LINK' },
  { symbol: 'LKMNH.IS', name: 'Lokman Hekim Engurusag', shortName: 'LKMNH' },
  { symbol: 'LMKDC.IS', name: 'Limak Doğu Anadolu Çimento', shortName: 'LMKDC' },
  { symbol: 'LOGO.IS', name: 'Logo Yazılım', shortName: 'LOGO' },
  { symbol: 'LRSHO.IS', name: 'Loras Holding', shortName: 'LRSHO' },
  { symbol: 'LUKSK.IS', name: 'Lüks Kadife', shortName: 'LUKSK' },
  { symbol: 'LXGYO.IS', name: 'Luxera GYO', shortName: 'LXGYO' },
  { symbol: 'LYDHO.IS', name: 'Lydia Holding', shortName: 'LYDHO' },
  { symbol: 'LYDYE.IS', name: 'Lydia Yeşil Enerji', shortName: 'LYDYE' },
  { symbol: 'MAALT.IS', name: 'Marmaris Altınyunus', shortName: 'MAALT' },
  { symbol: 'MACKO.IS', name: 'Maçkolik', shortName: 'MACKO' },
  { symbol: 'MAGEN.IS', name: 'Margün Enerji', shortName: 'MAGEN' },
  { symbol: 'MAKIM.IS', name: 'Makim Makina', shortName: 'MAKIM' },
  { symbol: 'MAKTK.IS', name: 'Makina Takım', shortName: 'MAKTK' },
  { symbol: 'MANAS.IS', name: 'Manas Enerji Yönetimi', shortName: 'MANAS' },
  { symbol: 'MARBL.IS', name: 'Tureks Turunç', shortName: 'MARBL' },
  { symbol: 'MARKA.IS', name: 'Marka Yatırım Holding', shortName: 'MARKA' },
  { symbol: 'MARMR.IS', name: 'Marmara Holding', shortName: 'MARMR' },
  { symbol: 'MARTI.IS', name: 'Martı Otel İşletmeleri', shortName: 'MARTI' },
  { symbol: 'MAVI.IS', name: 'Mavi Giyim Sanayi Tic.A.S', shortName: 'MAVI' },
  { symbol: 'MCARD.IS', name: 'MetropolCard', shortName: 'MCARD' },
  { symbol: 'MEDTR.IS', name: 'Meditera Tıbbi Malzeme', shortName: 'MEDTR' },
  { symbol: 'MEGAP.IS', name: 'Mega Polietilen Köpük', shortName: 'MEGAP' },
  { symbol: 'MEGMT.IS', name: 'Mega Metal', shortName: 'MEGMT' },
  { symbol: 'MEKAG.IS', name: 'Meka Beton', shortName: 'MEKAG' },
  { symbol: 'MEPET.IS', name: 'Metro Petrol ve Tesisleri', shortName: 'MEPET' },
  { symbol: 'MERCN.IS', name: 'Mercan Kimya', shortName: 'MERCN' },
  { symbol: 'MERIT.IS', name: 'Merit Turizm Yatırım', shortName: 'MERIT' },
  { symbol: 'MERKO.IS', name: 'Merko Gıda', shortName: 'MERKO' },
  { symbol: 'METRO.IS', name: 'Metro Tic. Mali Yat.', shortName: 'METRO' },
  { symbol: 'MEYSU.IS', name: 'Meysu Gıda', shortName: 'MEYSU' },
  { symbol: 'MGROS.IS', name: 'Migros', shortName: 'MGROS' },
  { symbol: 'MHRGY.IS', name: 'Mhr GYO', shortName: 'MHRGY' },
  { symbol: 'MIATK.IS', name: 'Mia Teknoloji', shortName: 'MIATK' },
  { symbol: 'MMCAS.IS', name: 'MMC San.ve Tic. Yatırımlar A.Ş', shortName: 'MMCAS' },
  { symbol: 'MNDRS.IS', name: 'Menderes Tekstil', shortName: 'MNDRS' },
  { symbol: 'MNDTR.IS', name: 'Mondi Tire', shortName: 'MNDTR' },
  { symbol: 'MOBTL.IS', name: 'Mobitel İletişim', shortName: 'MOBTL' },
  { symbol: 'MOGAN.IS', name: 'Mogan Enerji', shortName: 'MOGAN' },
  { symbol: 'MOPAS.IS', name: 'Mopaş', shortName: 'MOPAS' },
  { symbol: 'MPARK.IS', name: 'MLP Sağlık Hizmetleri', shortName: 'MPARK' },
  { symbol: 'MRGYO.IS', name: 'Martı GYO', shortName: 'MRGYO' },
  { symbol: 'MRSHL.IS', name: 'Marshall', shortName: 'MRSHL' },
  { symbol: 'MSGYO.IS', name: 'Mistral GYO', shortName: 'MSGYO' },
  { symbol: 'MTRKS.IS', name: 'Matriks Finansal Teknolojiler', shortName: 'MTRKS' },
  { symbol: 'MTRYO.IS', name: 'Metro YO', shortName: 'MTRYO' },
  { symbol: 'MZHLD.IS', name: 'Mazhar Zorlu Holding', shortName: 'MZHLD' },
  { symbol: 'NATEN.IS', name: 'Naturel Yenilenebilir Enerji', shortName: 'NATEN' },
  { symbol: 'NETAS.IS', name: 'Netaş', shortName: 'NETAS' },
  { symbol: 'NETCD.IS', name: 'Netcad Yazılım', shortName: 'NETCD' },
  { symbol: 'NIBAS.IS', name: 'Niğde Beton Sanayi', shortName: 'NIBAS' },
  { symbol: 'NTGAZ.IS', name: 'Naturel Gaz', shortName: 'NTGAZ' },
  { symbol: 'NTHOL.IS', name: 'Net Holding', shortName: 'NTHOL' },
  { symbol: 'NUGYO.IS', name: 'Nurol GYO', shortName: 'NUGYO' },
  { symbol: 'NUHCM.IS', name: 'Nuh Çimento', shortName: 'NUHCM' },
  { symbol: 'OBAMS.IS', name: 'Oba Makarnacılık', shortName: 'OBAMS' },
  { symbol: 'OBASE.IS', name: 'Obase Bilgisayar Danışmanlık', shortName: 'OBASE' },
  { symbol: 'ODAS.IS', name: 'Odaş Elektrik Üretim', shortName: 'ODAS' },
  { symbol: 'ODINE.IS', name: 'Odine Solutions', shortName: 'ODINE' },
  { symbol: 'OFSYM.IS', name: 'Ofis Yem', shortName: 'OFSYM' },
  { symbol: 'ONCSM.IS', name: 'Oncosem', shortName: 'ONCSM' },
  { symbol: 'ONRYT.IS', name: 'Onur Yüksek Teknoloji', shortName: 'ONRYT' },
  { symbol: 'ORCAY.IS', name: 'Ortaköy Çay Sanayi', shortName: 'ORCAY' },
  { symbol: 'ORGE.IS', name: 'ORGE Enerji Elektrik', shortName: 'ORGE' },
  { symbol: 'ORMA.IS', name: 'Orma Orman Mahsulleri', shortName: 'ORMA' },
  { symbol: 'OSMEN.IS', name: 'Osmanlı Menkul Değ.', shortName: 'OSMEN' },
  { symbol: 'OSTIM.IS', name: 'Ostim Endüst. Yatırımlar', shortName: 'OSTIM' },
  { symbol: 'OTKAR.IS', name: 'Otokar', shortName: 'OTKAR' },
  { symbol: 'OTTO.IS', name: 'Otto Holding', shortName: 'OTTO' },
  { symbol: 'OYAKC.IS', name: 'Oyak Çimento', shortName: 'OYAKC' },
  { symbol: 'OYAYO.IS', name: 'Oyak Yatırım Ortaklığı', shortName: 'OYAYO' },
  { symbol: 'OYLUM.IS', name: 'Oylum Sınai Yatırımlar', shortName: 'OYLUM' },
  { symbol: 'OYYAT.IS', name: 'Oyak Yatırım', shortName: 'OYYAT' },
  { symbol: 'OZATD.IS', name: 'Özata Denizcilik', shortName: 'OZATD' },
  { symbol: 'OZGYO.IS', name: 'Özderici GYO', shortName: 'OZGYO' },
  { symbol: 'OZKGY.IS', name: 'Özak GYO', shortName: 'OZKGY' },
  { symbol: 'OZRDN.IS', name: 'Özerden Plastik', shortName: 'OZRDN' },
  { symbol: 'OZSUB.IS', name: 'Özsu Balık', shortName: 'OZSUB' },
  { symbol: 'OZYSR.IS', name: 'Özyaşar Tel', shortName: 'OZYSR' },
  { symbol: 'PAGYO.IS', name: 'Panora GYO', shortName: 'PAGYO' },
  { symbol: 'PAHOL.IS', name: 'Pasifik Holding', shortName: 'PAHOL' },
  { symbol: 'PAMEL.IS', name: 'Pamel Yenilenebilir Elekt.', shortName: 'PAMEL' },
  { symbol: 'PAPIL.IS', name: 'Papilon Savunma', shortName: 'PAPIL' },
  { symbol: 'PARSN.IS', name: 'Parsan', shortName: 'PARSN' },
  { symbol: 'PASEU.IS', name: 'Pasifik Eurasia', shortName: 'PASEU' },
  { symbol: 'PATEK.IS', name: 'Pasifik Teknoloji', shortName: 'PATEK' },
  { symbol: 'PCILT.IS', name: 'PC İletişim ve Medya', shortName: 'PCILT' },
  { symbol: 'PEKGY.IS', name: 'Peker GYO', shortName: 'PEKGY' },
  { symbol: 'PENGD.IS', name: 'Penguen Gıda', shortName: 'PENGD' },
  { symbol: 'PENTA.IS', name: 'Penta Teknoloji', shortName: 'PENTA' },
  { symbol: 'PETKM.IS', name: 'Petkim', shortName: 'PETKM' },
  { symbol: 'PETUN.IS', name: 'Pınar Et ve Un', shortName: 'PETUN' },
  { symbol: 'PGSUS.IS', name: 'Pegasus Hava Taşımacılığı', shortName: 'PGSUS' },
  { symbol: 'PINSU.IS', name: 'Pınar Su', shortName: 'PINSU' },
  { symbol: 'PKART.IS', name: 'Plastikkart A.Ş', shortName: 'PKART' },
  { symbol: 'PKENT.IS', name: 'Petrokent', shortName: 'PKENT' },
  { symbol: 'PLTUR.IS', name: 'Platform Turizm', shortName: 'PLTUR' },
  { symbol: 'PNLSN.IS', name: 'Panelsan Çatı Cephe', shortName: 'PNLSN' },
  { symbol: 'PNSUT.IS', name: 'Pınar Süt', shortName: 'PNSUT' },
  { symbol: 'POLHO.IS', name: 'Polisan Holding', shortName: 'POLHO' },
  { symbol: 'POLTK.IS', name: 'Politeknik Metal', shortName: 'POLTK' },
  { symbol: 'PRDGS.IS', name: 'Pardus Girişim', shortName: 'PRDGS' },
  { symbol: 'PRKAB.IS', name: 'Prysmian Kablo', shortName: 'PRKAB' },
  { symbol: 'PRKME.IS', name: 'Park Elek. Madencilik', shortName: 'PRKME' },
  { symbol: 'PRZMA.IS', name: 'Prizma Pres Matbaacılık', shortName: 'PRZMA' },
  { symbol: 'PSDTC.IS', name: 'Pergamon Status', shortName: 'PSDTC' },
  { symbol: 'PSGYO.IS', name: 'Pasifik GYO', shortName: 'PSGYO' },
  { symbol: 'QNBFK.IS', name: 'QNB Finans Fin. Kir.', shortName: 'QNBFK' },
  { symbol: 'QNBTR.IS', name: 'QNB Bank', shortName: 'QNBTR' },
  { symbol: 'QUAGR.IS', name: 'QUA Granite', shortName: 'QUAGR' },
  { symbol: 'RALYH.IS', name: 'Ral Yatırım Holding', shortName: 'RALYH' },
  { symbol: 'RAYSG.IS', name: 'Ray Sigorta', shortName: 'RAYSG' },
  { symbol: 'REEDR.IS', name: 'Reeder', shortName: 'REEDR' },
  { symbol: 'RGYAS.IS', name: 'Rönesans Gayrimenkul', shortName: 'RGYAS' },
  { symbol: 'RNPOL.IS', name: 'Rainbow Polikarbonat', shortName: 'RNPOL' },
  { symbol: 'RODRG.IS', name: 'Rodrigo Tekstil', shortName: 'RODRG' },
  { symbol: 'RTALB.IS', name: 'RTA laboratuvarlari', shortName: 'RTALB' },
  { symbol: 'RUBNS.IS', name: 'Rubenis Tekstil', shortName: 'RUBNS' },
  { symbol: 'RUZYE.IS', name: 'Ruzy Madencilik ve Enerji', shortName: 'RUZYE' },
  { symbol: 'RYGYO.IS', name: 'Reysaş GYO', shortName: 'RYGYO' },
  { symbol: 'RYSAS.IS', name: 'Reysaş Taşımacılık', shortName: 'RYSAS' },
  { symbol: 'SAFKR.IS', name: 'Safkar Ege Soğutmacılık', shortName: 'SAFKR' },
  { symbol: 'SAHOL.IS', name: 'Sabancı Holding', shortName: 'SAHOL' },
  { symbol: 'SAMAT.IS', name: 'Saray Matbaacılık', shortName: 'SAMAT' },
  { symbol: 'SANEL.IS', name: 'San-El Muhendislik', shortName: 'SANEL' },
  { symbol: 'SANFM.IS', name: 'Sanifoam Sünger Sanayi', shortName: 'SANFM' },
  { symbol: 'SANKO.IS', name: 'Sanko Pazarlama', shortName: 'SANKO' },
  { symbol: 'SARKY.IS', name: 'Sarkuysan', shortName: 'SARKY' },
  { symbol: 'SASA.IS', name: 'Sasa Polyester Sanayi A.Ş.', shortName: 'SASA' },
  { symbol: 'SAYAS.IS', name: 'Say Yenilenebilir Enerji', shortName: 'SAYAS' },
  { symbol: 'SDTTR.IS', name: 'SDT Uzay', shortName: 'SDTTR' },
  { symbol: 'SEGMN.IS', name: 'Seğmen Gıda', shortName: 'SEGMN' },
  { symbol: 'SEGYO.IS', name: 'Şeker GYO', shortName: 'SEGYO' },
  { symbol: 'SEKFK.IS', name: 'Şeker Finansal Kiralama A.Ş', shortName: 'SEKFK' },
  { symbol: 'SEKUR.IS', name: 'Sekuro Plastik', shortName: 'SEKUR' },
  { symbol: 'SELEC.IS', name: 'Selçuk Ecza Deposu', shortName: 'SELEC' },
  { symbol: 'SELVA.IS', name: 'Selva Gıda', shortName: 'SELVA' },
  { symbol: 'SERNT.IS', name: 'Seranit Granit', shortName: 'SERNT' },
  { symbol: 'SEYKM.IS', name: 'Seyitler Kimya', shortName: 'SEYKM' },
  { symbol: 'SILVR.IS', name: 'Silverline', shortName: 'SILVR' },
  { symbol: 'SISE.IS', name: 'Şişecam', shortName: 'SISE' },
  { symbol: 'SKBNK.IS', name: 'Şekerbank', shortName: 'SKBNK' },
  { symbol: 'SKTAS.IS', name: 'Söktaş', shortName: 'SKTAS' },
  { symbol: 'SKYLP.IS', name: 'Skyalp Fin. Tek.ve Danışmanlık', shortName: 'SKYLP' },
  { symbol: 'SKYMD.IS', name: 'Şeker Yatırım', shortName: 'SKYMD' },
  { symbol: 'SMART.IS', name: 'Smartiks Yazılım', shortName: 'SMART' },
  { symbol: 'SMRTG.IS', name: 'Smart Güneş Enerjisi', shortName: 'SMRTG' },
  { symbol: 'SMRVA.IS', name: 'Sümer Varlık Yönetim', shortName: 'SMRVA' },
  { symbol: 'SNGYO.IS', name: 'Sinpas GYO', shortName: 'SNGYO' },
  { symbol: 'SNICA.IS', name: 'Sanica Isı Sanayi', shortName: 'SNICA' },
  { symbol: 'SNPAM.IS', name: 'Sönmez Pamuklu', shortName: 'SNPAM' },
  { symbol: 'SODSN.IS', name: 'Sodaş Sodyum Sanayii', shortName: 'SODSN' },
  { symbol: 'SOKE.IS', name: 'Söke Değirmencilik', shortName: 'SOKE' },
  { symbol: 'SOKM.IS', name: 'Şok Marketler', shortName: 'SOKM' },
  { symbol: 'SONME.IS', name: 'Sönmez Filament', shortName: 'SONME' },
  { symbol: 'SRVGY.IS', name: 'Servet GYO', shortName: 'SRVGY' },
  { symbol: 'SUMAS.IS', name: 'Sumas Mobilya', shortName: 'SUMAS' },
  { symbol: 'SUNTK.IS', name: 'Sun Tekstil', shortName: 'SUNTK' },
  { symbol: 'SURGY.IS', name: 'Sur GYO', shortName: 'SURGY' },
  { symbol: 'SUWEN.IS', name: 'Suwen Tekstil', shortName: 'SUWEN' },
  { symbol: 'SVGYO.IS', name: 'Savur GYO', shortName: 'SVGYO' },
  { symbol: 'TABGD.IS', name: 'Tab Gıda', shortName: 'TABGD' },
  { symbol: 'TARKM.IS', name: 'Tarkim', shortName: 'TARKM' },
  { symbol: 'TATEN.IS', name: 'Tatlıpınar Enerji', shortName: 'TATEN' },
  { symbol: 'TATGD.IS', name: 'Tat Gıda', shortName: 'TATGD' },
  { symbol: 'TAVHL.IS', name: 'TAV Holding', shortName: 'TAVHL' },
  { symbol: 'TBORG.IS', name: 'Tuborg', shortName: 'TBORG' },
  { symbol: 'TCELL.IS', name: 'Turkcell', shortName: 'TCELL' },
  { symbol: 'TCKRC.IS', name: 'Kıraç Galvaniz', shortName: 'TCKRC' },
  { symbol: 'TDGYO.IS', name: 'Trend GYO', shortName: 'TDGYO' },
  { symbol: 'TEHOL.IS', name: 'Tera Holding', shortName: 'TEHOL' },
  { symbol: 'TEKTU.IS', name: 'Tek-Art Turizm', shortName: 'TEKTU' },
  { symbol: 'TERA.IS', name: 'Tera Yatırım', shortName: 'TERA' },
  { symbol: 'TEZOL.IS', name: 'Europap Tezol', shortName: 'TEZOL' },
  { symbol: 'TGSAS.IS', name: 'TGS Dış Ticaret', shortName: 'TGSAS' },
  { symbol: 'THYAO.IS', name: 'Türk Hava Yolları', shortName: 'THYAO' },
  { symbol: 'TKFEN.IS', name: 'Tekfen Holding', shortName: 'TKFEN' },
  { symbol: 'TKNSA.IS', name: 'Teknosa İç ve Dış Tic.', shortName: 'TKNSA' },
  { symbol: 'TLMAN.IS', name: 'Trabzon Liman İşletmeciliği', shortName: 'TLMAN' },
  { symbol: 'TMPOL.IS', name: 'TE-MAPOL Polimer Plastik', shortName: 'TMPOL' },
  { symbol: 'TMSN.IS', name: 'Tümosan Motor ve Traktör', shortName: 'TMSN' },
  { symbol: 'TNZTP.IS', name: 'Tapdi Oksijen', shortName: 'TNZTP' },
  { symbol: 'TOASO.IS', name: 'Tofaş Fabrika', shortName: 'TOASO' },
  { symbol: 'TRALT.IS', name: 'Türk Altın', shortName: 'TRALT' },
  { symbol: 'TRCAS.IS', name: 'Turcas Holding', shortName: 'TRCAS' },
  { symbol: 'TRENJ.IS', name: 'TR Doğal Enerji Kaynakları', shortName: 'TRENJ' },
  { symbol: 'TRGYO.IS', name: 'Torunlar GYO', shortName: 'TRGYO' },
  { symbol: 'TRHOL.IS', name: 'Tera Finansal Yat. Holding', shortName: 'TRHOL' },
  { symbol: 'TRILC.IS', name: 'Turk İlaç ve Serum Sanayi', shortName: 'TRILC' },
  { symbol: 'TRMET.IS', name: 'TR Anadolu Metal', shortName: 'TRMET' },
  { symbol: 'TSGYO.IS', name: 'TSKB GYO', shortName: 'TSGYO' },
  { symbol: 'TSKB.IS', name: 'TSKB', shortName: 'TSKB' },
  { symbol: 'TSPOR.IS', name: 'Trabzonspor A.Ş', shortName: 'TSPOR' },
  { symbol: 'TTKOM.IS', name: 'Türk Telekom', shortName: 'TTKOM' },
  { symbol: 'TTRAK.IS', name: 'Türk Traktör', shortName: 'TTRAK' },
  { symbol: 'TUCLK.IS', name: 'Tuğçelik Alüminyum ve Metal', shortName: 'TUCLK' },
  { symbol: 'TUKAS.IS', name: 'Tukaş', shortName: 'TUKAS' },
  { symbol: 'TUPRS.IS', name: 'Tüpraş', shortName: 'TUPRS' },
  { symbol: 'TUREX.IS', name: 'Tureks Tur.Taşımacılık', shortName: 'TUREX' },
  { symbol: 'TURGG.IS', name: 'Türker Proje Gay.Gel.', shortName: 'TURGG' },
  { symbol: 'TURSG.IS', name: 'Türkiye Sigorta', shortName: 'TURSG' },
  { symbol: 'UCAYM.IS', name: 'Üçay Mühendislik', shortName: 'UCAYM' },
  { symbol: 'UFUK.IS', name: 'Ufuk Yat.Yön.ve Gay. AŞ.', shortName: 'UFUK' },
  { symbol: 'ULAS.IS', name: 'Ulaşlar Turizm Yatırımları', shortName: 'ULAS' },
  { symbol: 'ULKER.IS', name: 'Ülker Bisküvi', shortName: 'ULKER' },
  { symbol: 'ULUFA.IS', name: 'Ulusal Faktoring', shortName: 'ULUFA' },
  { symbol: 'ULUSE.IS', name: 'Ulusoy Elektrik', shortName: 'ULUSE' },
  { symbol: 'ULUUN.IS', name: 'Ulusoy Un', shortName: 'ULUUN' },
  { symbol: 'UNLU.IS', name: 'Ünlü Yatırım Holding', shortName: 'UNLU' },
  { symbol: 'USAK.IS', name: 'Uşak Seramik', shortName: 'USAK' },
  { symbol: 'VAKBN.IS', name: 'Vakıfbank', shortName: 'VAKBN' },
  { symbol: 'VAKFA.IS', name: 'Vakıf Faktoring', shortName: 'VAKFA' },
  { symbol: 'VAKFN.IS', name: 'Vakıf Fin. Kir.', shortName: 'VAKFN' },
  { symbol: 'VAKKO.IS', name: 'Vakko Tekstil', shortName: 'VAKKO' },
  { symbol: 'VANGD.IS', name: 'Vanet Gıda Sanayi', shortName: 'VANGD' },
  { symbol: 'VBTYZ.IS', name: 'VBT Yazılım', shortName: 'VBTYZ' },
  { symbol: 'VERTU.IS', name: 'Verusatürk Girişim Sermayesi', shortName: 'VERTU' },
  { symbol: 'VERUS.IS', name: 'Verusa Holding', shortName: 'VERUS' },
  { symbol: 'VESBE.IS', name: 'Vestel Beyaz Esya', shortName: 'VESBE' },
  { symbol: 'VESTL.IS', name: 'Vestel Elektronik', shortName: 'VESTL' },
  { symbol: 'VKFYO.IS', name: 'Vakıf YO', shortName: 'VKFYO' },
  { symbol: 'VKGYO.IS', name: 'Vakıf GYO', shortName: 'VKGYO' },
  { symbol: 'VKING.IS', name: 'Viking Kağıt', shortName: 'VKING' },
  { symbol: 'VRGYO.IS', name: 'Vera GYO', shortName: 'VRGYO' },
  { symbol: 'VSNMD.IS', name: 'Vişne Madencilik', shortName: 'VSNMD' },
  { symbol: 'YAPRK.IS', name: 'Yaprak Süt & Besi Çiftlikleri', shortName: 'YAPRK' },
  { symbol: 'YATAS.IS', name: 'Yataş Yatak', shortName: 'YATAS' },
  { symbol: 'YAYLA.IS', name: 'Yayla Enerji Uretim Turizm', shortName: 'YAYLA' },
  { symbol: 'YBTAS.IS', name: 'Yibitaş İnş. Malzemeleri', shortName: 'YBTAS' },
  { symbol: 'YEOTK.IS', name: 'YEO Teknoloji', shortName: 'YEOTK' },
  { symbol: 'YESIL.IS', name: 'Yeşil Yatırım Holding', shortName: 'YESIL' },
  { symbol: 'YGGYO.IS', name: 'Yeni Gimat GYO', shortName: 'YGGYO' },
  { symbol: 'YGYO.IS', name: 'Yeşil GYO', shortName: 'YGYO' },
  { symbol: 'YIGIT.IS', name: 'Yiğit Akü', shortName: 'YIGIT' },
  { symbol: 'YKBNK.IS', name: 'Yapı Kredi Bankası', shortName: 'YKBNK' },
  { symbol: 'YKSLN.IS', name: 'Yükselen Çelik', shortName: 'YKSLN' },
  { symbol: 'YONGA.IS', name: 'Yonga Mobilya Sanayi', shortName: 'YONGA' },
  { symbol: 'YUNSA.IS', name: 'Yünsa', shortName: 'YUNSA' },
  { symbol: 'YYAPI.IS', name: 'Yesil Yapi', shortName: 'YYAPI' },
  { symbol: 'YYLGD.IS', name: 'Yayla Agro Gıda', shortName: 'YYLGD' },
  { symbol: 'ZEDUR.IS', name: 'Zedur Enerji', shortName: 'ZEDUR' },
  { symbol: 'ZERGY.IS', name: 'Zeray GYO', shortName: 'ZERGY' },
  { symbol: 'ZGYO.IS', name: 'Z GYO', shortName: 'ZGYO' },
  { symbol: 'ZOREN.IS', name: 'Zorlu Enerji', shortName: 'ZOREN' },
  { symbol: 'ZRGYO.IS', name: 'Ziraat GYO', shortName: 'ZRGYO' },
];

// BIST En Likit Hisseler - Tarama için (98 adet)
export const BIST_TOP_CODES = new Set([
  'A1CAP', 'ACSEL', 'AEFES', 'AGHOL', 'AHGAZ', 'AKBNK', 'AKCNS', 'AKENR', 'AKFGY', 'AKSA',
  'AKSEN', 'ALARK', 'ALFAS', 'ALKIM', 'ARCLK', 'ARDYZ', 'ARENA', 'ASELS', 'ASTOR', 'AYDEM',
  'BERA', 'BFREN', 'BIMAS', 'BIOEN', 'BRSAN', 'BRYAT', 'BTCIM', 'BUCIM', 'CANTE', 'CCOLA',
  'CIMSA', 'CWENE', 'DOAS', 'ECILC', 'EGEEN', 'EKGYO', 'ENJSA', 'ENKAI', 'EREGL', 'EUPWR',
  'FROTO', 'GARAN', 'GESAN', 'GUBRF', 'GWIND', 'HALKB', 'HEKTS', 'ISCTR', 'ISGYO', 'ISMEN',
  'KCHOL', 'KLSER', 'KONTR', 'KRDMD', 'KTLEV', 'KZBGY', 'LOGO', 'MAVI', 'MGROS', 'MIATK',
  'ODAS', 'OTKAR', 'OYAKC', 'PETKM', 'PGSUS', 'QUAGR', 'SAHOL', 'SASA', 'SDTTR', 'SISE',
  'SKBNK', 'SMRTG', 'SOKM', 'TABGD', 'TATGD', 'TAVHL', 'TCELL', 'THYAO', 'TKFEN', 'TKNSA',
  'TOASO', 'TRGYO', 'TSKB', 'TTKOM', 'TTRAK', 'TUKAS', 'TUPRS', 'TURSG', 'ULKER', 'VAKBN',
  'VESBE', 'VESTL', 'YEOTK', 'YKBNK', 'YYLGD', 'ZOREN', 'ZRGYO', 'AGESA',
]);

export const BIST_TOP_STOCKS: BistAsset[] = BIST_ALL_STOCKS.filter(s => BIST_TOP_CODES.has(s.shortName));

// Borsa Yatırım Fonları (30 adet)
export const BIST_FUNDS: BistAsset[] = [
  { symbol: 'APGLD.IS', name: 'Ak Portföy Altın BYF', shortName: 'APGLD' },
  { symbol: 'APMDL.IS', name: 'Ak Portföy BIST 100 Model BYF', shortName: 'APMDL' },
  { symbol: 'APX30.IS', name: 'Ak Portföy BIST 30 BYF', shortName: 'APX30' },
  { symbol: 'APBDL.IS', name: 'Ak Portföy Banka Dışı Likit 10 BYF', shortName: 'APBDL' },
  { symbol: 'APLIB.IS', name: 'Ak Portföy Likit Banka BYF', shortName: 'APLIB' },
  { symbol: 'ISGLK.IS', name: 'İş Portföy Altın BYF', shortName: 'ISGLK' },
  { symbol: 'NPTLR.IS', name: 'Nurol Portföy TLREF BYF', shortName: 'NPTLR' },
  { symbol: 'OPX30.IS', name: 'Osmanlı Portföy BIST 30 BYF', shortName: 'OPX30' },
  { symbol: 'OPT25.IS', name: 'Osmanlı Portföy Temettü 25 BYF', shortName: 'OPT25' },
  { symbol: 'OPTLR.IS', name: 'Osmanlı Portföy TLREF BYF', shortName: 'OPTLR' },
  { symbol: 'OPTGY.IS', name: 'Osmanlı Portföy GYO BYF', shortName: 'OPTGY' },
  { symbol: 'OPK30.IS', name: 'Osmanlı Portföy Katılım 30 BYF', shortName: 'OPK30' },
  { symbol: 'GLDTR.IS', name: 'QNB Portföy Altın BYF', shortName: 'GLDTR' },
  { symbol: 'USDTR.IS', name: 'QNB Portföy USD BYF', shortName: 'USDTR' },
  { symbol: 'GMSTR.IS', name: 'QNB Portföy Gümüş BYF', shortName: 'GMSTR' },
  { symbol: 'QTEMZ.IS', name: 'QNB Portföy Temiz Enerji BYF', shortName: 'QTEMZ' },
  { symbol: 'ZGOLD.IS', name: 'Ziraat Portföy Altın BYF', shortName: 'ZGOLD' },
  { symbol: 'ZPX30.IS', name: 'Ziraat Portföy BIST 30 BYF', shortName: 'ZPX30' },
  { symbol: 'Z30EA.IS', name: 'Ziraat Portföy BIST 30 Eşit Ağırlıklı BYF', shortName: 'Z30EA' },
  { symbol: 'ZELOT.IS', name: 'Ziraat Portföy BIST 50-30 BYF', shortName: 'ZELOT' },
  { symbol: 'ZPBDL.IS', name: 'Ziraat Portföy Banka Dışı Likit 10 BYF', shortName: 'ZPBDL' },
  { symbol: 'Z30KP.IS', name: 'Ziraat Portföy Katılım 30 BYF', shortName: 'Z30KP' },
  { symbol: 'Z30KE.IS', name: 'Ziraat Portföy Katılım 30 Eşit Ağırlıklı BYF', shortName: 'Z30KE' },
  { symbol: 'ZPLIB.IS', name: 'Ziraat Portföy Likit Banka BYF', shortName: 'ZPLIB' },
  { symbol: 'ZSR25.IS', name: 'Ziraat Portföy Sürdürülebilirlik 25 BYF', shortName: 'ZSR25' },
  { symbol: 'ZTM25.IS', name: 'Ziraat Portföy Temettü 25 BYF', shortName: 'ZTM25' },
  { symbol: 'ZTLRF.IS', name: 'Ziraat Portföy TLREF BYF', shortName: 'ZTLRF' },
  { symbol: 'ZTLRK.IS', name: 'Ziraat Portföy TLREFK Katılım BYF', shortName: 'ZTLRK' },
  { symbol: 'ZRE20.IS', name: 'Ziraat Portföy Risk Eşit Banka Dışı 20 BYF', shortName: 'ZRE20' },
  { symbol: 'ZPT10.IS', name: 'Ziraat Portföy Teknoloji 10 BYF', shortName: 'ZPT10' },
];

// Tüm BIST Varlıkları (hisse + fon)
export const BIST_ALL_ASSETS: BistAsset[] = [...BIST_ALL_STOCKS, ...BIST_FUNDS];
