import { createElement } from 'react';
import { act, create, type ReactTestRenderer } from 'react-test-renderer';
import { afterEach, beforeEach, expect, it, vi } from 'vitest';
const push = vi.hoisted(() => vi.fn());
vi.mock('next/navigation', () => ({ useRouter: () => ({ push }) }));
vi.mock('next/link', () => ({ default: (props: any) => createElement('a', props) }));
import { BeginnerGuide } from '../components/beginner-guide';
import { Onboarding } from '../components/onboarding';
import { guideDismissed } from '../lib/guide-client';
beforeEach(() => { push.mockReset(); });
afterEach(() => { vi.unstubAllGlobals(); });
const button = (view: ReactTestRenderer, text: string) => view.root.findAllByType('button').find(b => b.children.join('') === text)!;
it('only offers the welcome to newly registered accounts and skipping is immediate even when saving fails', async () => {
  const fetcher = vi.fn().mockResolvedValueOnce(Response.json({ step: 0, status: 'new' })).mockResolvedValueOnce(Response.json({}, { status: 503 }));
  vi.stubGlobal('fetch', fetcher);
  let view!: ReactTestRenderer;
  await act(async () => { view = create(createElement(Onboarding, { accountId: 'new-skip' })); });
  expect(button(view, 'Rehbere başla')).toBeTruthy();
  await act(async () => button(view, 'Şimdilik atla').props.onClick());
  expect(view.toJSON()).toBeNull(); expect(guideDismissed('new-skip')).toBe(true);
  expect(guideDismissed('another-account')).toBe(false);
  expect(JSON.parse(fetcher.mock.calls[1][1].body).status).toBe('skipped');
  act(() => view.unmount());
  await act(async () => { view = create(createElement(Onboarding, { accountId: 'new-skip' })); });
  expect(fetcher).toHaveBeenCalledTimes(2);
  act(() => view.unmount());
});
it('leaves existing members undisturbed', async () => {
  vi.stubGlobal('fetch', vi.fn().mockResolvedValue(Response.json({ step: 0, status: 'available' })));
  let view!: ReactTestRenderer;
  await act(async () => { view = create(createElement(Onboarding, { accountId: 'existing' })); });
  expect(view.toJSON()).toBeNull(); act(() => view.unmount());
});
it('resumes a skipped lesson, calculates an isolated example, saves progress and completes without sending trades', async () => {
  const fetcher = vi.fn().mockImplementation(async (_url, options) => Response.json(options?.method ? {} : { step: 2, status: 'skipped' }));
  vi.stubGlobal('fetch', fetcher);
  let view!: ReactTestRenderer;
  await act(async () => { view = create(createElement(BeginnerGuide, { accountId: 'learner' })); });
  expect(view.root.findByType('h1').children.join('')).toBe('Sanal alım formunu anla');
  act(() => view.root.findByType('input').props.onChange({ target: { value: '3' } }));
  expect(JSON.stringify(view.toJSON())).toContain('Örnek toplam: 300 TL');
  act(() => view.root.findByType('input').props.onChange({ target: { value: '-2' } }));
  expect(JSON.stringify(view.toJSON())).not.toContain('Örnek toplam: -');
  await act(async () => button(view, 'Devam').props.onClick());
  expect(JSON.parse(fetcher.mock.calls[1][1].body)).toEqual({ step: 3, status: 'in_progress' });
  await act(async () => button(view, 'Devam').props.onClick());
  await act(async () => button(view, 'Rehberi tamamla').props.onClick());
  expect(view.root.findByType('h1').children.join('')).toBe('Rehberi tamamladın');
  expect(fetcher.mock.calls.every(call => call[0] === '/api/onboarding')).toBe(true);
  act(() => view.unmount());
});
it('does not advance after a failed save and always allows skipping', async () => {
  const fetcher = vi.fn().mockResolvedValueOnce(Response.json({ step: 1, status: 'in_progress' })).mockResolvedValue(Response.json({}, { status: 503 }));
  vi.stubGlobal('fetch', fetcher);
  let view!: ReactTestRenderer;
  await act(async () => { view = create(createElement(BeginnerGuide, { accountId: 'failed-save' })); });
  await act(async () => button(view, 'Devam').props.onClick());
  expect(view.root.findByType('h1').children.join('')).toBe('Bir hisseyi keşfet');
  expect(view.root.findByProps({ role: 'alert' })).toBeTruthy();
  await act(async () => button(view, 'Şimdilik atla').props.onClick());
  expect(push).toHaveBeenCalledWith('/dashboard');
  act(() => view.unmount());
});
it('does not overwrite unknown progress when loading fails', async () => {
  const fetcher = vi.fn().mockRejectedValue(new Error('offline')); vi.stubGlobal('fetch', fetcher);
  let view!: ReactTestRenderer;
  await act(async () => { view = create(createElement(BeginnerGuide, { accountId: 'failed-load' })); });
  expect(button(view, 'Devam')).toBeUndefined();
  expect(view.root.findByProps({ role: 'alert' })).toBeTruthy();
  await act(async () => button(view, 'Şimdilik atla').props.onClick());
  expect(fetcher).toHaveBeenCalledTimes(1);
  act(() => view.unmount());
});
